name: CI/CD Pipeline

on:
    push:
        branches: ["main"]
    workflow_dispatch: # Permite ejecución manual con botón

jobs:
    # JOB 1: BACKEND AUTH
    build-auth-server:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"
                  cache: "maven"
            - name: Grant execute permission for mvnw
              run: chmod +x authorization-server/mvnw
            - name: Build Authorization Server
              run: cd authorization-server && ./mvnw clean package -DskipTests

    # JOB 2: BACKEND RESOURCE
    build-resource-server:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"
                  cache: "maven"
            - name: Grant execute permission for mvnw
              run: chmod +x resource-server/mvnw
            - name: Build Resource Server
              run: cd resource-server && ./mvnw clean package -DskipTests

    # JOB 3: FRONTEND
    build-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"
                  cache-dependency-path: ag-prueba-front/package-lock.json
            - name: Install Dependencies
              run: cd ag-prueba-front && npm ci
            - name: Build Angular
              run: cd ag-prueba-front && npm run build -- --configuration=production

    # JOB 4: DEPLOY SIMULATION
    deploy:
        needs: [build-auth-server, build-resource-server, build-frontend]
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        environment: Production
        steps:
            - name: Simulate Deployment
              run: echo "🚀 Deploying version ${{ github.sha }} to production..."
